version: '3.8'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:55553 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
        - 55553
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=2827
      - DATABASE_URL=postgresql://postgres:pass@localhost:55554
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - DATABASE=postgres
      - APP_FOLDER=/usr/src/app
    depends_on:
      - postgres
  
  postgres:
    build: services/postgres
    volumes:
      - ./:/tmp/db
      - postgres_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 55554:5432
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 55553:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  postgres_prod:
